### ISSUE TITLE
short form accessibility

### ISSUE THREAD

**Issue by mcfrank** [langcog/web-cdi#101]
if short forms were available, these could be available to all researchers (prior to entering into agreement for use of long-form data in renorming). (see #100)

**Comment by mcfrank** [comment]
this one appears to be broadly accessible...

**Comment by vmarchman** [comment]
English Level 1, Level 2AB need instructions

**Comment by HenryMehta** [comment]
The issue with the instructions is the program is looking for a form of WS or WG and it selects instructions accordingly.  I have changed this so it looks for WG and provides those instructions.  When the for is not WG it assumes WS and shows those instructions (I did it this way because I believe all short forms are currently WS).  Going forward, we must ensure all WG forms have WG stated as the form within `instruments.json`

This is in dev for testing.

An alternative approach would be to change the forms to be called WS (or WG) for the existing items, however this will create a new instrument and instrument items (ie the system will not apply it to the current forms and studies but create a new set of forms).  This would be more consistent with system design.

**Comment by vmarchman** [comment]
Not all short forms are WS.  Level 1 is WG short form; the two Level 2 forms are WS.  CDI III is something completely different (I'm realizing now), and may require tweak to the instructions.  I would opt for alternative approach.

**Comment by HenryMehta** [comment]
ok - In that case the best approach is to amend the html file.  I've now set the if clause to provide the WG instructions if the form is WG or L1 and provide the WS instructions if the form is L2A or L2B.  We'll need to include a new clause for CDI III.

You should be able to test this now
