### ISSUE TITLE
increase upper limit of age window

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#121]
Currently upper limit is 50 months for W&G.  Researchers working with Autism, Angelman's syndrome, etc., have children with lower levels of language.  Request that upper limit be increased to at least 96 months.

**Comment by HenryMehta** [comment]
@vmarchman This looks like a database, rather than code, setting.  I believe you need someone with an admin account to login and change the max_age for that instrument.  This would be logging in as admin, going to Home > Researcher UI > instrument and selecting the relevant instrument then changing the value from 50 to 96 and saving the record.

I do not have an admin login so cannot test locally.

**Comment by HenryMehta** [comment]
This is a change in `webcdi/researcher_UI/static/researcher_UI/add_study_modal.html` where 50 needs changing to 96 on line 29.

Part of commit 600ed242
