### ISSUE TITLE
fix registration form so it directs to email

### ISSUE THREAD

**Issue by mcfrank** [langcog/web-cdi#123]
https://webcdi.stanford.edu/registration/register/

this form should go to webcdi-contact@stanford.edu but currently we don't know where it goes.

**Comment by HenryMehta** [comment]
This is a self registration form.  Reading the code, the form is being sent to the email entered into the E-mail field on the form.  This sends out an Activation Email and by clicking the link in that email the account should be activated.  I haven't tried completing the form to confirm this is correct, but this is how the django-registration package works I cannot see code amending it.

I need to know what you would like to happen

**Comment by HenryMehta** [comment]
I have added singals processing so that when a new registration is created an email will be sent (commit: a1c8c5ef).

This requires an email to be added to settings.py (or email.py) called USER_ADMIN_EMAIL.  This value will be set to the desired recipient, so given the initial requirement

`USER_ADMIN_EMAIL = 'webcdi-contact@stanford.edu'`
