### ISSUE TITLE
change permissions on table

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#124]
cdi_forms_instrument_forms

**Comment by HenryMehta** [comment]
@vmarchman What permissions need changing?

**Comment by HenryMehta** [comment]
![Pasted File at March 14, 2019 11:44 AM](https://user-images.githubusercontent.com/10542767/54475072-0e080400-47e5-11e9-9d45-c48263e8a759.png)

The attachment is (part of) the script that is failing.  I cannot see any table permission differences here (on my local version) and I need to repeat the error so I can identify the issue.  Can I have a copy of the code being run and I'll see if I can progress from there.

**Comment by HenryMehta** [comment]
The problem here isn't permissions.  The problem is the database structure has been changed.  Within this code:

```
form_info <- get_common_table(webcdi, "researcher_UI_instrument") %>%
  collect() %>%
  split(.$name) %>%
  map_df(function(x) {
    y <- get_common_table(webcdi, paste("cdi_forms", tolower(first(x$name)), sep="_")) %>% 
      collect() %>% 
      mutate(instrument = first(x$name),
             language = first(x$language),
             form = first(x$form)) %>%
      rename(item_ID = itemID)
    return(y)
  }) %>% 
  filter(!grepl('example', item_ID))

```
 The line `y <- get_common_table(webcdi, paste("cdi_forms", tolower(first(x$name)), sep="_")) %>%` is creating a string `cdi_forms_english_l1` and then trying to access that table within the database.  That table (and similar tables such as `cdi_forms_english_l2`) have been removed and replaced with a single table `cdi_forms_instrument_forms` and within this there is a field, `instrument_id` which specifies the form being used.

I do not know R so I do not know how to change this but we need to change the line to `y <- get_common_table(webcdi, "cdi_forms_instrument_forms") %>%` and then filter on the `instrument_id` field.

**Comment by HenryMehta** [comment]
Actually I think it is a little more complicated than this.  I don't think `cdi_forms_instrument_forms` replaced the other tables as previously suggested, but something has and I'm trying to work out what has.  I'll do this by trying to review migrations files.
