### ISSUE TITLE
Server Error (500) when trying to register a new user

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#129]
When completing form at https://webcdi.stanford.edu/registration/register/, completing form returns a Server Error (500).  Admins can still add users manually.

**Comment by vmarchman** [comment]
Can add users manually, but when that user tries to change pre-set password, get the same Server Error (500)!

**Comment by HenryMehta** [comment]
This is working for me locally so I'm not sure what is happening - investigating

**Comment by HenryMehta** [comment]
The issue is the `email.py` settings.  The email and password being used to send emails are no longer valid.  I have temporarily implemented emails using my SendGrid account.  This would be a good solution for you since there are no charges if you send under 100 emails per day.  Otherwise you need to provide new email credentials to fix this.

**Comment by HenryMehta** [comment]
New email now in dev and will go live with next commit to master
