### ISSUE TITLE
server 500 error when using single reusable links

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#139]
From Eva Lai (Hong Kong group): When I tried to open the single reusable link for “mass distribution of this study with other studies within its group”, an error message was returned “Server Error (500)”. The link does not work.

**Comment by HenryMehta** [comment]
@vmarchman I'm trying to replicate this error on the development server and I can't.  If I cannot replicate it I cannot work out the error to fix it

**Comment by mcfrank** [comment]
let's see if we can get Eva tagged directly so she can give screenshots
etc.?

**Comment by vmarchman** [comment]
yes - I asked her to do that this morning.  no word yet.

**Comment by HenryMehta** [comment]
Adding note from Eva below

> Hi Virginia,
> 
> I first logged in my researcher account. I grouped four studies (WG English, WG Spanish, WS English, WS Spanish) and named the group as “R21”. Then I chose one study of the group, hitted “Add Participants”, and checked on the URL “Single Reusable Link”, i.e. the one that is described “for mass distribution of this study along with other studies within its group”. It directed to a page showing “Server Error (500)”. You may also see the attached screen recording for reference.
> 
> Thanks,
> 
> Eva

**Comment by HenryMehta** [comment]
@vmarchman @mcfrank Can anyone confirm if this functionality did work at some point.  I'm looking through the code and it is trying to use an object it hasn't initialised which is why it is erroring.  If this used to work, a merge has taken place where code has overwritten working code and I need to find where that change took place - I can then put the code back in.

On the other hand, if it has never worked, I need to work out what it was trying to do and complete the process.

**Comment by vmarchman** [comment]
I do know that the single usable link worked with our facebook studies and it seems to work now.  The only difference in Eva's case is that she is grouping the studies.  I've never done that nor have I heard of Danielle doing that. My suspicion is that is where things are going wrong.

**Comment by HenryMehta** [comment]
Yes, this is where it is going wrong.  Once a study is grouped there are two choices of link to create (the current one plus a grouped version of the link).  The grouped version doesn't work.  It's code is also in a strange place (not really in keeping with the program logic)

**Comment by HenryMehta** [comment]
@vmarchman 
I'm amended this so that the single reusable link within the Group area isn't there.  This is because it doesn't work and I've looked at the code from pre me, and it is the same code so it never worked.  I think we close this and if someone explains what is required we open a new item and I develop it.
