### ISSUE TITLE
unable to update study information

### ISSUE THREAD

**Issue by benjamindemayo** [langcog/web-cdi#140]
The following workflow leads to a bug for me:

1) Creating a new study
2) Update study
3) Adding Amazon gift cards & their amounts in the window that pops up to add the study information
4) Trying to click 'submit' or 'close' -- this is where it breaks. I can't successfully close the study information window to return back to the main page for the study, even if I try clicking the X in the top right corner.

**Comment by HenryMehta** [comment]
@benjamindemayo I presume this used to work.  Can you confirm and confirm when you last used it and it worked (an approximate date so I can see what changes have been made since it did work)

**Comment by vmarchman** [comment]
Now, when I test, it will not give me an error when I leave the gift card amount blank.

**Comment by hilary-rose** [comment]
This seems similar to an issue I recently encountered, which I will outline here:

Popups and their "submit" buttons work inconsistently--on an HP desktop computer, I clicked the "new study" button to create a test study for checking something, and after pressing "submit", the popup didn't change or go away, so it seemed like it wasn't working, but when I refreshed the page, the changes were actually made in the list of studies. The behaviour of the popups/submit buttons is confusing because it doesn't seem like the action has any effect, and the popup does not go away until you refresh the page. **I was using Windows 10 and the most up to date version of Google Chrome when this error occurred**. I also had a similar error occur using an iPad, but it's working now that I have updated the iOS.

**Comment by HenryMehta** [comment]
@hilary-rose I am unable to replicate this error in Firefox or Chrome (I am using Linux rather than Windows 10).  Could you do me a favour (and I am sorry to ask this but I don't have the right PC to test this) ...  

Using Chrome could you select New Study the right click on the popup window and from the menu that appears select "Inspect" (it should be at the bottom).  This will open a new Tab/Window or Frame within the current page.  Please select 'Console' from that new window.  Now do whatever you did to create the new study without the popup showing and then could you send me a screen shot of the of the 'Console'.  This will show me if the are specific Windows 10/Chrome errors.

Thank you

**Comment by hilary-rose** [comment]
Hi Henry,

Here is the screenshot for Windows 10. Please let me know if I can help in any other way!

Hilary

![image](https://user-images.githubusercontent.com/52216858/62149360-8caf9a80-b2c9-11e9-8194-916967a3ef57.png)

**Comment by HenryMehta** [comment]
@hilary-rose 
I've had my son try this from his Windows 10 PC and he isn't getting this error.  I'm a little flummoxed about how to deal with this.  I have one idea which is to remove the `fade` class from the modal.  This will mean the modal comes instantly rather than smoothly.  It is a known error for specific versions of Bootstrap and hopefully it will sort it.   

Since I cannot replicate it and nor can my son, could I ask you to test again please.  Thank you.  

It should be ready to test in about 5 minutes

**Comment by hilary-rose** [comment]
Hi @HenryMehta,

I tested this again, and I had no problems and no errors showed up in the Console panel (hence, nothing to screenshot for you). I think this fixed the issue!
