### ISSUE TITLE
use item names instead of item numbers in csv item-level output

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#142]

**Comment by HenryMehta** [comment]
I've implemented this on Download Data > Download Data (CSV format) and Download Selected Data > Download Selected Data (CSV/All).  If have used the definition field rather than the gloss field (although we should probably use gloss).

The definition field describes the item in the language of the survey (so dog in English would be chien in French).  The gloss for the field should be dog in both all languages.  I used definition because I am not certain the gloss is completed on all languages.  I can change to gloss if you prefer (will need to for multiple survey analysis) and we will need to check all languages have the gloss completed correctly.

Please test and confirm preferred approach.

**Comment by HenryMehta** [comment]
I've modified this so where a gloss exists, it is used and where it doesn't exist, it uses the definition.

The French WS currently has no gloss so shows the definition (in French).  The Spanish WS has a gloss so shows the gloss (which is in English).
