### ISSUE TITLE
Skip logic

### ISSUE THREAD

**Issue by Cielke-Hendriks** [langcog/web-cdi#158]
We would like to have skip logic in the questionnaire. One use would be to skip to the end of the questionnaire if the parents do not tick the box to give consent.

**Comment by HenryMehta** [comment]
@Cielke-Hendriks Can you explain this a bit more - if they've have not consented they shouldn't see any of the form.

**Comment by Cielke-Hendriks** [comment]
Yes. We would have a consent form at the beginning (Is there already (a possibility to have) a consent form?). If they don't give consent (tick a box), they should not be able to see the form. And thus be directed to the/a end of the questionnaire. Does this help?

**Comment by HenryMehta** [comment]
I believe this functionality is already in place.  In the Update Study pop up complete something in Waiver information.  The respondent then has to agree to this info to progress to completing the study

**Comment by HenryMehta** [comment]
Approach:  Within Waiver documentation add option to say No, which will close the whole Tab

**Comment by HenryMehta** [comment]
@vmarchman @Cielke-Hendriks 
I've amended the waiver functionality following discussions with @Cielke-Hendriks because previously there was no option to say No so a respondent could simple press escape and enter data even if they hadn't actively agreed. 

I've removed the ability to escape out of the modal and I've added a 'No' button. When the 'No' button is selected, the respondent is presented with a new modal that says they cannot proceed and please close the window (it also gives them an option to review the consent again).
