### ISSUE TITLE
Confusing error message in French form

### ISSUE THREAD

**Issue by hilary-rose** [langcog/web-cdi#167]
We had a participant attempt to fill out the Quebec French Mots et Gestes Web-CDI, but got stuck very early on by a confusing error message. Please see the attachment:
![WebCDIError](https://user-images.githubusercontent.com/52216858/62056491-c4e0ab80-b1eb-11e9-817e-022b4c75e331.jpg)

The text box for "De qui?" means "from who?" but the error message "ne peut pas être plus que 18 semaines d'avance" means "cannot be more than 18 weeks early". It seems that this error message might relate to a question about gestation length, and is showing up in the wrong place. The researcher went through all the previous responses with the parent and they looked fine, so it wasn't clear why this error was appearing. In the end, the parent filled out the CDI on paper since they couldn't move the Web-CDI forward at this point.

I tried to recreate this error message by making a test subject and entering nonsensical data, but no matter what I tried I could not get the same error to appear.

Do you have any insight into this?

Thank you!

**Comment by HenryMehta** [comment]
Wow - this is a great error and is highlighting another error.  The problem is there are two errors on the submitted form.  First, they've said the child was born more than 18 months in advance.  It has caught this error but the code is telling it to show it in the wrong place.  I have corrected this.  
The second error is the De qui hasn't been completed and it should be getting an error message "Ce champ ne peut pas être vide" but it is only apply the error if the field isn't returned at all or is returned as "".  It is actually being returned as None

I've corrected this now.  You can test by:
1. Trying born more than 18 weeks in advance or more than 4 weeks in arrears
AND
2. Saying yes to some of the Health questions but not completing the text fields which appear

**Comment by HenryMehta** [comment]
@hilary-rose Can you test quickly and confirm you're happy with this.  Thanks

**Comment by HenryMehta** [comment]
@hilary-rose - planning to put this to production tomorrow - can you confirm it is working please.
Thank you

**Comment by hilary-rose** [comment]
@HenryMehta Hi Henry, I just did a test and the error messages seem to make sense now. And, when I correct the responses, the CDI allows me to continue. So I think this has been fixed, thank you!
