### ISSUE TITLE
In Quebec French data, more than one column have same name

### ISSUE THREAD

**Issue by hilary-rose** [langcog/web-cdi#171]
I've been working on developing a script to work with the Web-CDI data, and I've run into a problem because in the Quebec French versions of Mots et Gestes and Mots et Enoncés, 3 column names are repeated and can't be differentiated from each other. Is it possible to change the column variable names to the below values? @HenryMehta 

**In Mots et Gestes:**
_bain_ is the column name for both columns 212 and 315. Can we change the first instance to **bain_object** and the second instance to **bain_routine**?

_poisson_ is the column name for both columns 120 and 167. Can we change the first instance to **poisson_animal** and the second instance to **poisson_food**?

_eau_ is the column name for both columns 155 and 277. Can we change the first instance to **eau_beverage** and the second instance to **eau_not_beverage**?

**In Mots et Enoncés:**
_bain_ is the column name for both columns 302 and 419. Can we change the first instance to **bain_object** and the second instance to **bain_routine**?

_poisson_ is the column name for both columns 94 and 181. Can we change the first instance to **poisson_animal** and the second instance to **poisson_food**?

_eau_ is the column name for both columns 158 and 344. Can we change the first instance to **eau_beverage** and the second instance to **eau_not_beverage**?

**Comment by hilary-rose** [comment]
Hi again,

I noticed a few more of these in the Words & Sentences/Mots et Enoncés forms. I will outline them below:

**In Mots et Enoncés:**
_poulet_ is the column name for both columns 96 and 186. Can we change the first instance to **poulet_animal** and the second instance to **poulet_food**?

_pot_ is the column name for both columns 288 and 328. Can we change the first instance to **pot_jar** and the second instance to **pot_potty**?

_fin_is__ is the column name for both columns 723 and 737. Can we change the first instance to **fin_is_1** and the second instance to **fin_is_2**?

_fini_ is the column name for both columns 576 and 733. Can we leave the first instance as it is, and change the second instance to **fini2**?

_bÃ¢ton_ is the column name for both columns 119 and 339. Can we change the first instance to **baton_bat** and the second instance to **baton_stick**?

_orange_ is the column name for both columns 175 and 593. Can we change the first instance to **orange_food** and the second instance to **orange_colour**?

**In Words and Sentences Canadian English**
_feet_ is the column name for both columns 243 and 740. Can we leave the first instance as it is, and change the second instance to **feet_plural**?

Thank you @HenryMehta !

**Comment by HenryMehta** [comment]
@vmarchman, @hilary-rose,
I think @hilary-rose is asking for this because they're getting mixed up in the downloads.  @vmarchman, I think this is happening because we've moved from using the `itemID` as a header to using the definition so it shows a sensible tile (eg eau rather than item_103).  But eau is now used in two places so the results will get amalgamated or one will be removed (I haven't checked which).  

If I change the wording as requested they'll show like this in the surveys.  I think the solution is to use the `item` rather than `itemID` for reporting purposes which I think is unique and is easy to read than the `itemID`.  At the moment the French files have eau1 and eau2 in `item` so by moving to that we'll be able to distinguish the different responses and we can modify to the longer names if requested.  

Please confirm you're ok for me to progress on this basis

   been looking at this and the error is caused because we've moved t

**Comment by vmarchman** [comment]
Hi @HenryMehta - that's a great solution, giving us informative but also
unique headers.  thanks.

**Comment by HenryMehta** [comment]
OK - I've made that change and it is going live now.  @hilary-rose, could you let me know if this gives you the distinction you need or if you still like me to make the changes specified.

Thanks
