### ISSUE TITLE
No way to limit participant per study

### ISSUE THREAD

**Issue by benjamindemayo** [langcog/web-cdi#179]
I think I've mentioned this in passing to @HenryMehta before, but on the `Update Study` tab there is an option to enter a maximum number of participants, but it seems to not have any functionality (in other words, if I try to limit the number of participants to 50, web-cdi will still let a 51st person and so on complete the survey).

**Comment by benjamindemayo** [comment]
I should mention that this option to limit participants only shows up if you check the `Do you plan on collecting only anonymous data in this study? (e.g., posting ads on social media, mass emails, etc)` box.

**Comment by HenryMehta** [comment]
@benjamindemayo @vmarchman 

I think I've worked out the issue here and I need some guidance on what you want.

This is what is happening:

When a parent clicks the Single Reusable Link (that I assume you are posting on Facebook), the program checks "completed" administrations rather than Clicked Links.  For example, if you set Maximum number of participants to 2 then the program will allow parent to click the link (and therefore create a new administration) until 2 parents have completed the survey.  Once the 2 parents have completed the survey any subsequent clicks on the link receive a page with the following

> Thank you!
> 
> Thank you for your interest in completing the MacArthur-Bates Communicative Development Inventory (CDI)! At this time, all of our study slots have already filled up and we have run out of thank-you gifts to compensate you for your time! If you are still interested in completing the CDI and learning more about your child's vocabulary, you may click here to complete the 30-minute questionnaire. If you have any concerns about your child’s development, we recommend that you talk with your child’s physician. If you enjoyed our assessment, you can learn more about the CDI here. Again, we appreciate your interest! 

Options:
1. Change the functionality so the check is based on number of administrations created rather than the number completed.  This should be relatively simple and if you haven't enough completed administrations then you could delete those not completed and although parents to follow the link again.  You would need to ensure no one is using this functionality in some other way currently.

2. Add functionality so that you can specify number of completed administrations and number of administrations to be created (by clicking the link).  If either are exceeded the parent will get the above page.  This is slightly more complicated to implement, but still relatively simple.

3. Leave functionality as it is and set the maximum number to some value below what is actually available

**Comment by benjamindemayo** [comment]
Thanks for this Henry. I think actually what we want is 3), leaving it as is, although this didn't seem to happen in my last few pilots - even after the completed administrations exceeded the limit set in the study settings, more people clicked the link and proceeded to complete the study. Maybe there is a small bug in the implementation? Sorry to not be able to provide more useful information.

**Comment by benjamindemayo** [comment]
To clarify - I think we ideally want this to check the number of completed administrations, but right now it doesn't seem to be doing that. In my last few studies, the system kept letting new people do the study after we had already blown past the limit I set for completed administrations.

**Comment by HenryMehta** [comment]
@benjamindemayo @vmarchman 

Assuming you are using the "Single Reusable Link" and having reviewed the code, I am certain it is checking the completed administrations.  I believe what is happening is administrations are being created before the completed limit is reached and are then completed after the limit is reached so you end up with too many administrations.  The way to check this is the issue is
1. find the first x administrations completed (where x is the maximum number you've set).  
2. find the last one completed from the first x using the Last Modified date/time (assuming you haven't changed any of the records).  Call this data/time StopStudyTime
3. compare the creation date/time of all other administrations.

If any creation data/time is greater than StopStudyTime then we are creating new administraions after we have the maximum number of completed administrations.  If the creation times are all before then we know it isn't allowing new administrations after the completed limit is reached.

If you tell me an example study where you have the problem with the maximum set, I'll download the data and do the analysis.

**Comment by benjamindemayo** [comment]
Thanks so much Henry. I also thought this might be the issue but there are too many extra administrations for this to likely be the case - in any case, the name of the study was `norming_pilot_wg_6_19`.

**Comment by HenryMehta** [comment]
@benjamindemayo @vmarchman 
Of your 655 responses, 44 were created after the 50th was completed.  

On the overflow page there is this sentence: "If you are still interested in completing the CDI and learning more about your child's vocabulary, you may click here to complete the 30-minute questionnaire". 

If you click here, a field in the backend is set showing they will forego payment.  The last 44 administrations created all have this field selected (and 17 completed the study).  None of the others do.

Please note, some administrations were created before the 50th completed administration was completed but completed after the 50th administration was completed.  These administrations will not have the forego payment checked and would expect payment.

**Comment by vmarchman** [comment]
@HenryMehta Ok, Benny and I talked and we understand the functionality now and will structure our workflow accordingly.

**Comment by vmarchman** [comment]
@HenryMehta We would like to change the text of the message to parents to more explicitly tell them that can continue to fill out the form, but they will not receive compensation.  I have edited the text below.

Thank you for your interest in completing the MacArthur-Bates Communicative Development Inventory (CDI)! At this time, all of our study slots have already filled up and we have run out of thank-you gifts to compensate you for your time. If you are still interested in completing the CDI and learning more about your child's vocabulary, you may click here to complete the questionnaire, but you will not receive compensation.  You can also keep an eye out for another study ad in the future!  If you have any concerns about your child’s development, we recommend that you talk with your child’s physician. If you enjoyed our assessment, you can learn more about the CDI here. Again, we appreciate your interest!
