### ISSUE TITLE
Make Web-CDI mobile friendly

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#187]
Need to explore how to make system more readable/usable on mobile platforms.

**Comment by HenryMehta** [comment]
I've been looking at the site on mobile.  I had previously looked at it using a screen replicator on a PC and it looks dreadful.  However, I've also just taken a look on my cell phone and it comes out looking ok.  I think before I do significant work on this I would like you to take a look but accessing a single reusable link from your cell and seeing what it looks like

**Comment by HenryMehta** [comment]
From @mcfrank 

> Things that look weird:
> - documentation waiver
> - calendar picker
> - would probably be a pain but optimally breaking demographics across pages
> - Word choice boxes are a bit misaligned and prob a bit too small

From @vmarchman 

> on Background form, response boxes, e.g., who is the primary caregiver, when you fill them out, the boxes are too small, so cuts off responses
> here is where it is annoying to have the instructions repeat on every page - as it fills up the entire page and you don't know you are on the next page until you scroll down 
> graph of responses does not appear at end.
> other than that, it doesn't look too terrible

I've made the calendar bigger and (although I think it easier to type it) and I've aligned and made the checkboxes bigger.
Given the work I've done for Dutch we could split the Demographics across pages but it would be Front and Back pages (ie one is after they've completed the study) and it would apply to the desktop version as well.  Doing something for cell's would not be quick.
I'm not sure what you want on the waiver - it looks the same as the desktop[ (perhaps a little small).

The dropdown select boxes are now bigger.
Amending instructions is big and not something to try quickly
Graph should be working - could you check for desktop.  Please note the Instrument you're using because it might be working for one and not the other (I had to make changes for Dutch which might have been missed in testing).

**Comment by HenryMehta** [comment]
Put Live 7th December 2019
