### ISSUE TITLE
WebCDI down

### ISSUE THREAD

**Issue by itang1** [langcog/web-cdi#195]
Hi,

Every time we try to researcher log in, we get a notification saying Server Error 500

Steps to reproduce:
* Go to webcdi.stanford.edu
* Click researcher login
* Server 500 error

**Comment by mcfrank** [comment]
thanks for reporting, I confirm this now. 

@HenryMehta any thoughts?

**Comment by HenryMehta** [comment]
@mcfrnk, @virginia

I have now investigated this.

It has been caused by the attempted upgrade on Thursday.  As part of the Python3.6 upgrade a database change was needed.  I ran directly against the production database which was clearly a mistake because the security certificate would not move.

A temporary solution is to log in as admin and the select view website followed by Researcher login.  Because the admin login doesn't access the same table a session cookie is created and you can proceed.  This would mean giving users is_staff access but not actually admin update functionality (which can all be done through the admin panel).

I have done this for @itang1 but can remove.  Other researchers will be having the same issue.

**Comment by itang1** [comment]
Thanks for looking into this
Our username is bergelsonlab

The error seems to have changed to 503 Service Temporarily Unavailable?

**Comment by HenryMehta** [comment]
Hi @itang1, In trying to sort this permanantly I have run into another issue which I need to sort first.  I do apologise - please bear with me

**Comment by itang1** [comment]
understood, thanks so much for your help!

**Comment by HenryMehta** [comment]
This should now be working - my apologies for the delay
