### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#212]
We are getting an Internal server error (see WebCDI slack channel for image) possibly intermittently.  We get it (1) logging into the researcher administration pages (tested with both langcoglab and marchman).
(2) sometimes when clicking on a particular administration or when clicking on the link for a new administration in the participant screen

When you refresh the page, the error resolves.

**Comment by HenryMehta** [comment]
@vmarchman 
I couldn't replicate this on my local set up or in webcdi-dev but I could replicate on production.  The only difference is production has a variable DEFAULT set to False rather than True with the other 2.  I needed to see the error message so I changed it to True and then couldn't replicate the error so I reverted to False and cannot replicate the error.

I've also tried on webcdi-dev to set DEBUG=False and create the error and I can't.

Could we track please and see if you can identify the steps that create the error.  Thank you

**Comment by HenryMehta** [comment]
Unable to replicate so closing
