### ISSUE TITLE
Move some background questions to end of form

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#225]
Move BIF questions to end of form to parallel Dutch.

**Comment by HenryMehta** [comment]
@vmarchman 
English WS2 is available to test in webcdi-dev.  I know the graphs and background information display isn't shown to parents (although I might be able to sort before you get to this.  I haven't tested Amazon vouchers.
I think the rest is working

**Comment by HenryMehta** [comment]
@vmarchman 
This is now all loaded and ready to test.  I've given you access to English WS2, English WG2, English L1B, English L2AB, English L2BB, Spanish WS2, Spanish WG2.

If given Krista (because I think she does the testing) access to French Quebec WS2, French Quebec WG2, Canadian English WS2, Canadian English WG2
