### ISSUE TITLE
Add explanatory text field in back part of background questions

### ISSUE THREAD

**Issue by Cielke-Hendriks** [langcog/web-cdi#249]
We would like to add explanatory text to the second part of the background questions (the back page in the Dutch form). Preferably in the position of the example below:

Vervolg achtergrondinformatie
*** Add extra explanation of questions here ***
Gezondheid en ontwikkeling van uw kind
Is uw kind te vroeg of te laat geboren (meer dan een week voor of na de uitgerekende datum)?*
Etc.

**Comment by HenryMehta** [comment]
Notes to myself:
This would mean changing the format of the json files to be
[
   "help_text" : "Some page header text",
  "fieldsets" : [{
      ... as now ...
   }]
]

I would then need to amend the form creator to read the help information and then the fieldsets (rather than just load the fieldsets) and would need to create some method for the form to pass none form data.

And then apply this to all json files for all languages.

**Comment by HenryMehta** [comment]
@Cielke-Hendriks 
I've added a new file with the naming format form_data/background_info/Dutch_WG_back_helptext.json  and the format

[{"help-text" : "The text you want as explanation"}]

**Comment by HenryMehta** [comment]
@Cielke-Hendriks available to test in 20 mins
