### ISSUE TITLE
Login page email to be specific to instance (ie Stanford or MPI)

### ISSUE THREAD

**Issue by HenryMehta** [langcog/web-cdi#287]
Hi Henry,

 

Hope you are well!

 

The ‘Web-CDI team’ in the home-page takes us to the webcdi-contact@stanford.edu. This should be webcdi@mpi.nl for us.

The secrets.py does have the variable CONTACT_EMAIL defined with the mpi id. And I do see it in the ‘contact us’ in the home page.

But I saw that this is not being used in the for the ‘Web-CDI team’ as it has been hard coded in the setting.py.

 

Can you please make it variable so that the code picks it from the secrets.py with the mpi CONTACT_EMAIL?

 

 

Kind Regards,

Pavithra

**Comment by HenryMehta** [comment]
@PaviSrinivasa 
I do not understand.  CONTACT_EMAIL and MORE_INFO_ADDRESS are defined in secret_settings.py (and they do not appear in settings.py).  webcdi/context_processors.py then uses these values and passes them to the templates.  The home page (for researchers) is found in researchers_UI/templates/researchers_UI/home.html where these values are used

**Comment by PaviSrinivasa** [comment]
@HenryMehta The issue is the 'Web-CDI Team' highlighted in the home page has the Stanford email address hardcoded in the HTML page. I am referring to Line 44 of the web-cdi/webcdi/webcdi/templates/home.html page in the code. It should be re-written such that it is picked up from the CONTACT_EMAIL variable as used in other places. It is the same for the researchers_UI/templates/researchers_UI/home.html with Line 54.

**Comment by HenryMehta** [comment]
@PaviSrinivasa 
Got it - thanks.
I've updated researcher_UI/templates>researcher_UI>home.html in the Spanish branch (which is the next to be moved to master).  This is in webcdi-dev.stanford.edu but will be showing the stanford email because I have that in secret settings.
Deploying now
Please confirm it looks right so I can change status to ready to go live - thanks.

**Comment by PaviSrinivasa** [comment]
@HenryMehta I tested in our local server and it works. Thanks Henry!
