### ISSUE TITLE
compute both chron and adjusted age for preterms

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#288]
Only one age is currently calculated based on DOB and DOCDI.  For children born preterm, it is common practice to compare to children based on adjusted age (i.e., age adjusted for degree of prematurity).  So, if parents indicated DOB in the usual spot, the age computed is chronological age.  How about adding to the preterm drop down a new computation of adjusted age based on the number of weeks premature?  Then, give the user the choice of generating percentiles based on chron age, adjusted age, or both....

**Comment by HenryMehta** [comment]
@vmarchman 
Is User in the above a Researcher and is this about downloading benchmark percentiles?  I assume yes to both below.

Given stats are now calculated and saved rather than calculated when the Researcher requests the data, we would need to know which date to use in advance.

We could either provide the data using both dates (ie benchmark for DOB and benchmark for adjusted DOB) or the Researcher would need to select the preferred benchmark DOB in advance and not be able to change it

**Comment by vmarchman** [comment]
Yes, this is about downloading benchmark percentiles.  I think let's download both percentiles, only in the cases when the parent indicates number of weeks born early.

**Comment by HenryMehta** [comment]
@vmarchman 
I've been looking at how to approach this issue this morning.  Because we now calculate scores as the survey is completed we need to make changes in that area and then in the download area.  This will mean that existing responses will not have the age adjusted data unless we recalculate the historically completed items as well.  Is this something you want me to do?

**Comment by HenryMehta** [comment]
@vmarchman Is this issue now covered by #397 ?

**Comment by vmarchman** [comment]
Yes @Henry ***@***.***>

**Comment by HenryMehta** [comment]
Merged into #397
