### ISSUE TITLE
English Level II - can't get passed demo

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#299]
I tried to complete an English Level IIA (short form) and the demographic information was at the end of the form.  The system would not let go passed the demo information to the splash page at the end.  When I returned to the researcher interface, the system said that the demo was completed, but not the form.

**Comment by HenryMehta** [comment]
@vmarchman 
I'm sorry but I do not quite understand but I think you're saying you couldn't get passed the demographic information at the end of the form.  I've tested and can.  So if this is the issues you're experiencing, please can you check that you're not trying to get passed before the minimum number of minutes to pass for the study have completed.

**Comment by HenryMehta** [comment]
@vmarchman Can you confirm if this is now working please - thank you

**Comment by vmarchman** [comment]
Hi @HenryMehta Ok, just did a thorough test of the English short forms.  You are right, the timing works just fine, but:

(1) English Level IA, Level IIA, Level IIB - the graph at the end is wrong.  It plots 100% of items (out of 12) rather than the actual proportion,

(2) English Level IAB, Level IIAB, Level IIBB

* In Demographic info, the question about "Are you Hispanic/Latino" is missing
* No picture instructions - should be the same as the other short/long forms.
* Graph is wrong at end as above - plotting 100% of items, rather than actual responses.

**Comment by HenryMehta** [comment]
@vmarchman 
Deploying to dev now
Are you Hispanic/Latino - done
Instructions - done
Graphs - I'm not sure if I've understood the error because the calculations and graphs look right to me (only did 1 test).  However, the horizontal scale was set to simply take account of percentage result rather than 100%.  I've assumed this is what you meant and forced the horizontal axis to 100%.  Please confirm if this was right

**Comment by vmarchman** [comment]
Thanks @HenryMehta.  Hispanic/Latino and Instructions work great. :-)

re Graphs:  Yes, the axis is now right, but two things:

(1) For Level IA and B - plot only includes Words Produced, not both Words Produced and Words Understood.
(2) For both Level I and II (A and B) - there's no text about "My child says X words" and "The hardest word my child says is X"

**Comment by HenryMehta** [comment]
@vmarchman 
Deploying changes now.  I think it all correct but please confirm.  It would be worth checking the changes I've made have not impacted the other forms.  I do not believe they have but a secondary check would be good

**Comment by vmarchman** [comment]
Hi @HenryMehta  - The short forms look good.  I checked the graphs on the long forms and it seems like we are missing some of the category labels on the graphs for the WG ones.  I'll slack you a screen shot.

**Comment by HenryMehta** [comment]
@vmarchman 
As you can see, on my screen all titles come out.  The problem is the amount of text relative to screen size.  I've amended the code to make the graphs 550px instead of 500px which I think/hope will help but if other languages have more text then they might still lose a title

![image](https://user-images.githubusercontent.com/10542767/98783122-f2f1fb00-23f0-11eb-8c6c-1687cca078cd.png)

**Comment by vmarchman** [comment]
Ok! @HenryMehta Looks good!
