### ISSUE TITLE
add mom year of birth to front end demo in all cases

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#300]
Right now, the mom year of birth question appears only in the front end demo if "show validation questions" is selected.  We would like that question to appear on the front end no matter what.  Then, we can use that question (along with the other demo questions that are already there) to cross-check across studies when one has the full demo and one has just the front end demo (and the back end turned off).

**Comment by HenryMehta** [comment]
@vmarchman 
Sorry to be a pain but I think I'm going to need more information here.  I need to understand when this shows and when it doesn't.  You need to think about all you other users and how they're currently using the system and if they want the mom DOB is all cases.  I'm assuming not (but happy to be wrong).

So I need to know when this automatically shows or what checkboxes you want in the  study spec in order to make sure the various options can be defined easily

**Comment by vmarchman** [comment]
@HenryMehta Good point.  Most users will use the Background in the front as the "standard" way.  We developed the back-end version for special use cases.  The "show validation questions" is checked by default, so hopefully, people will not turn off the back end questions, unless they know what they are doing.  And, it turns out that mom year of birth is problematic because of the "primary" vs. "secondary" caregiver labeling issue.  How about adding child birthweight to the front and back in all cases?

**Comment by HenryMehta** [comment]
@vmarchman 
Sorry to check again but I want to be 100% certain I understand what you want.  Are you saying to include child birth weight confirmation on front and back demographic pages (when demographic information is split) irrespective of whether the confirmation checkbox is ticked?

I am not keen on doing this because it will impact all other split demographic studies.  Furthermore, it breaks further the flexible approach used for the split page demographics because at the moment every form can have a different set of front and back page questions.  You will be forcing this onto the front page for all so if someone decides to put the birth weight on the front page, they would have both birth weight and confirmation of birth weight.

>  And, it turns out that mom year of birth is problematic because of the "primary" vs. "secondary" caregiver labeling issue.
I do not understand what the issue is here (except the label is confusing).  Primary care giver information is ALWAYS stored in the mother fields and secondary information is ALWAYS stored in the FATHER fields.  So if someone says primary caregiver is the father then you need to look at the mother_yob to get the yob of the father.

**Comment by vmarchman** [comment]
Hi @HenryMehta .  Yes, let's forget about the mother/father year of birth issue and leave it as currently coded. What we are really asking is simply to put child birth weight in the front rather than the back.  It doesn't need to be a confirmation question.  It would live next to the other questions on the front for the front only case, and only once in the front (and not the back) on the split (front/back case).   Let me know if this clears things up or if you would like to chat.  I think @JMankewitz should join so that we are all on the same page.

**Comment by HenryMehta** [comment]
@vmarchman @JMankewitz 
Yes, this can be done simply by changing the background info json (as specified here: https://github.com/langcog/web-cdi/wiki/Bespoke-Background-Information) for the English WS form (or English WG).  This will change it for all users of the English form.

An alternative would be to create a new form (Stanford Pilot WS) which has exactly the same inputs as the English WS but uses a different background info input json.  Let me know which you prefer.

**Comment by JMankewitz** [comment]
We've decided that instead of mother yob, we should use child birthweight. This is referenced in #303

**Comment by JMankewitz** [comment]
Same as #303, we won't be changing the location of the child's birthweight question.
