### ISSUE TITLE
Miscoding "primary caregiver" as "mother"

### ISSUE THREAD

**Issue by JMankewitz** [langcog/web-cdi#301]
Hello! 

It seems that a couple of the data columns code the primary caregiver as "mother" and the secondary caregiver as "father". Specifically, `mother_yob`, `mother_education`, `mother_yob_confirmation` are linked to the primary caregiver, regardless of who is identified as the primary caregiver. These should be changed to `primary_yob`, `primary_education`, `primary_yob_confirmation` (in line with the current `primary_caregiver` field.

The same issue for `father_yob` and `father_education`; these should be relabeled as `secondary_yob` and `secondary_education`.

**Comment by HenryMehta** [comment]
@JMankewitz @vmarchman 
Hi Jess, the system was originally built with the mother assumed to be primary and father secondary.  Although we changed the names presented to users we have not changed the field names because changing the field names would mean going through a huge amount of code.

I can do this but it will take me some time and you would then need to test all aspects of the system (and I even include language translations in that).  Please confirm if you want this done

**Comment by vmarchman** [comment]
Thanks, Henry.  I think for now we can live with it the way it is.  ok @JMankewitz ?

**Comment by JMankewitz** [comment]
Okay! This is fine. We can switch them in analysis.
