### ISSUE TITLE
add birthweight to front end demo in all cases

### ISSUE THREAD

**Issue by JMankewitz** [langcog/web-cdi#303]
As a followup to #300 instead of mom birthyear we want to add birthweight to the front end demographics page. The goal here is to use birthweight to compare participants across multiple forms. At a minimum, this means that _every_ participant needs to be asked the birthweight, including participants who are only getting the front end demographic questions.

We need to add birthweight to the current set of questions that appear in all cases, even when the backend is toggled off (currently this is `child_dob`,`child_sex`, `country`)

**Comment by HenryMehta** [comment]
@JMankewitz @vmarchman 
I need this specified with reference to how all the other forms work and not just for the CATCDI pilot so that you can use it in the CATCDI pilot, or wherever it is to be used.

The way this is currently specified it will mean that mother date of birth is required on all administrations, whether using split demographics or single demographics and whether part of the CATCDI or not.

I do not believe this is what you want.  Also, as I explained in issue #300, I need to if you want this to be done via the functionality delivered in the split demographics form or if you want it as an extra field to be added

**Comment by JMankewitz** [comment]
As per conversation over slack, we've decided not to change the location of the birthweight question so that it does not effect CDIs that have specific background information requirements. Thank you for the clarification @HenryMehta!
