### ISSUE TITLE
(suggestion/request) likheart/radio buttons for agree-disagree questions

### ISSUE THREAD

**Issue by JMankewitz** [langcog/web-cdi#320]
Is it too painful to implement a likheart scale for the agree-disagree and how often questions for the centiment demographics (instead of a dropdown)? 

Something like https://pypi.org/project/django-likert-field/

Or radio buttons (preferably horizontal)

https://stackoverflow.com/questions/5935546/align-radio-buttons-horizontally-in-django-forms

**Comment by HenryMehta** [comment]
This shouldn't be difficult to apply as long as @vmarchman confirms this is how she wants to proceed.  I suggest we hold off for the pilot study, like some of the other elements, to ensure you can proceed this week.  I don't want to apply more than needed because of the additional error risk

**Comment by vmarchman** [comment]
ok - I agree that the dropdowns are not ideal, but workable for now.  Thanks @HenryMehta

**Comment by vmarchman** [comment]
I agree that the dropdowns are not ideal and would prefer the other format
in the long run.  But, I don't think it makes that much difference for a
pilot.

**Comment by vmarchman** [comment]
@HenryMehta Sorry, but consensus is that it is really important to have the responses to the new questions be a likert scale with radio buttons, rather than a drop down.  We are willing to wait for that fix.  Hopefully, it won't be too hard to implement.

**Comment by HenryMehta** [comment]
@vmarchman @JMankewitz 
This has proven significantly more difficult than I anticipated.  https://pypi.org/project/django-likert-field/ is 5 years old and doesn't work with Django 2.  I have been able to amend it so it creates the right structures, but I cannot get it to provide a star rating system.

I've also spent some time looking at these packages https://djangopackages.org/grids/g/rating/.  These basically only apply 1 rating per model (rather than per question) so I cannot use this to apply the star ratings.
I've there just moved to Radio Select buttons and implemented that.

Deploying now - I hope it is ok
