### ISSUE TITLE
Change "submit" button and language

### ISSUE THREAD

**Issue by JMankewitz** [langcog/web-cdi#327]
Hi Henry! 

We have a change that will probably effect all of the English administrations, but it seems important now that all administrations can have a backpage. Right now the green "submit" button at the end of the questionaire can be confusing if the participant is actually directed to more questions. We propose the following changes: 

* Change the text on the button from `Submit` to `Next`

* Change the text on the popup from  "Are you ready to submit? You cannot change your answers after submission." to "Are you ready to move on? You cannot change your answers after this point."

We assume this change will effect more than just the centiment CDI administration, but we think its worth doing anyway. We understand we don't have the translations for the button, but we can add in the translations if we feel this is worth doing on other administrations.

Because it is aesthetic, I assume it can be pushed directly to prod, but let me know if you feel differently or are worried about other conflicts.

**Comment by HenryMehta** [comment]
@JMankewitz @vmarchman 

I'll pick both this and 328 up tomorrow morning my time so hopefully be available in dev for you when you get going.  There is an issue with this one for the other languages.

If I change the current text, when it tries to translate it will not find these strings in the translation files so will print these rather than the current translations.  "Are you ready to submit?" isn't an issue because I can just apply current translations to that since it isn't anywhere else but Submit is in several places (as is Next), so changing it to Next will change it on everyone's studies.

Please confirm that is ok

**Comment by vmarchman** [comment]
@Henry <hjsmehta@gmail.com>  Ok - Not quite sure I have it, but I think
you're saying that the issue is with changing the word "submit" to "next"
in the green box.

Are there implications for changing the text in the dialog box?

If not, is this a good solution?

* Keep the text in the Green box as currently is ("submit")

* Change the text in the dialog box that pops up to:  "Are you ready to
move on? You cannot change your answers after this point."

Not sure that this solves the problem.

**Comment by HenryMehta** [comment]
@vmarchman  @JMankewitz there are implications with both bits because with the "Are you ..." I will have to work through all the other translation files and add the current translation to this new sentence.  But this is manageable because we can make it look like it is not impacting the other languages. (please note there is a potential I'll make a mistake cut and pasting these translations - I am most worried about Hebrew and Korean).

The Submit changing to Next will reflect across all languages.  We can do that if you're happy to change it for all languages (and I do not see why they would complain because I think it is better).  Or we can just change the 1 bit as suggested.  

I don't mind which, I just want to make you aware of the impacts

**Comment by JMankewitz** [comment]
Hi! I think this is a change we should consider for the future, but lets put a pause on it for now. #328 is higher priority for this morning.

**Comment by HenryMehta** [comment]
@JMankewitz Is this change still required? If yes, now or still on hold?

**Comment by vmarchman** [comment]
@Henry ***@***.***> No, I think we can delete this and if it comes
up again, we can put a new issue.
