### ISSUE TITLE
answers switch languages in 

### ISSUE THREAD

**Issue by vmarchman** [langcog/web-cdi#330]
When doing the CAT, after some responses, the language switches from YES and NO to other languages (e.g., French, Korean).

**Comment by HenryMehta** [comment]
@vmarchman 
I cannot work out how to test this in order to recreate and then remove the issue.  What I think it happening is that with multiple users using the system at the same time, for some reason user A's language (not CAT) is getting applied to a CAT user.  I've added some code which I think will force the CAT study to use that user's language, but I'm not convinced I can test adequately so once I've checked it is running in development, I'm going to deploy direct to production

**Comment by HenryMehta** [comment]
@vmarchman 
I've tested as well as I can and I've deployed it to production.  I'll leave the issue open for a while.  Please let me know if it happens again.
Thanks
