### ISSUE TITLE
accepting payments for webCDI

### ISSUE THREAD

**Issue by mcfrank** [langcog/web-cdi#380]
@HenryMehta we would like to begin to accept credit card payments to license the use of the CAT instruments (not any other instruments at present). We know this is a big feature, but we have approval from Stanford to do this and we think it will pay for the long term expenses of the CAT. 

Licensing model will be that a single account will pay $500/year for unlimited access to the CAT. This fee will only be for commercial users. Non-commercial will continue to be free. 

We can accept payments via Stanford Merchant Services: https://fingate.stanford.edu/receipts-gifts/accepting-credit-and-debit-card-payments#anchor-24546. They recommend [CyberSource](https://www.cybersource.com/en-us/solutions/payment-acceptance.html).

So, the specific features we will need include:
1. a payments page that takes credit card info and licenses an account for a year
2. associate accounts with yearly licenses
3. check for license validity when you use CAT, spit out a warning if it's less than a month until expiration, block if you're expired

How does this sound? 
@vmarchman @kachergis

**Comment by mcfrank** [comment]
possibly a 2-year option for $900...

**Comment by HenryMehta** [comment]
hi mike,
What is the priority of this against Wordbank and Argentian CDI

**Comment by mcfrank** [comment]
Wordbank2 is the highest priority, this is next. Once we launch wordbank2,
then this would come next.

thanks,

**Comment by HenryMehta** [comment]
@mcfrank @vmarchman @JMankewitz 
I had already promised Mariela I would start on Argentinian WG this week and have done so because this will need database changes.  The LockIt development also requires database changes so I cannot park LockIt (#374) and develop this piece of work.  I either need to bin LockIt (knowing what I've previously done) or put it to production.  

I would prefer to put it to production and you simply not use it, but you would need to confirm that it doesn't impact other code/processes by testing the equivalents already in place

**Comment by mcfrank** [comment]
Let's push the lookit feature to production and @JMankewitz will test that it doesn't break anything. 

We will hold off on the licensing feature until after Argentine Spanish. 

thanks Henry!

**Comment by HenryMehta** [comment]
@mcfrank @vmarchman @JMankewitz @kachergis 

I'll be able to start on this once CATCDI testing is complete and I've put it live and I just want to play back my understanding in slightly different wording to ensure I understand.  Then I have some questions.

We are going to introduce a new type of researcher account (commercial user) that through payment of a licence fee, will have access to any and all CAT CDIs.  It is not a licence fee for each different CAT CDI but for the functionality.  They will not have access to the other CDIs.

They will gain access via licence which will last for 12 months from day of purchase.  During that time they can use the system as much as they want.  

During the last 30 days of the licence they should, when logging in, be shown a message advising them to extend the licence.  

They can extend at any time and the extension will be 12 months from expiry date or today, whichever is furtherest into the future.


I'm sure I'll have more questions, but to get started:

Once the licence has expired will they have access to their data to download it, even though they can no longer create new studies or are they completely blocked from logging into the system?

Once  a licence has expired, should any parent attempting to complete a previously sent link be blocked/prevented from completing (I assume yes, but just checking)?

Do you want an email sent once a week during last 30 days to remind them to renew licence?

Currently, when a researcher applies for access they need to be confirmed by an administrator.  Do you want the registration page changed such that there is a check box for "Commerical User" which will automatically register the user and automatically give them access to the CAT CDIs?

Do you want functionality to prevent an administrator from giving a Commercial User access to non CAT CDIs?

Do you want licence expiry date shown on the Researcher Interface so they always have a reminder?

Do I need to know anything about taxes?  I assume this is being billed in California so do I need to add state taxes or anything like that to the $500, or is it included in the $500.  Does this need to be separate line items for the user?  

Do we need to provide the user with an invoice and a receipt and anything else (I'm thinking about them claiming back from their employer and the employer being able to do their tax)?  

I have assumed only accepting credit and debit cards.  Not accepting cheques, bank transfers etc.  Please confirm.

I've not used CyberSource before, but I have used Stripe (it is on the list of approved gateways) which provides a very simple redirect to take a credit card payment and pass it back.  Would you be happy using that instead?  Do you want me to approach Merchant Services to arrange?

Do you want to change the Researcher Interface to make it multilingual?  At the moment English is forced on everyone

Do you want a x day free trial available in order to encourage trying it out?

**Comment by mcfrank** [comment]
Hi Henry, we are a go for moving forward with this project!

We are actually going to sell licenses under the scheme in the attached. 
[Web-CDI Proposal to Brookes, May 2022.docx](https://github.com/langcog/web-cdi/files/9537715/Web-CDI.Proposal.to.Brookes.May.2022.docx)

The spec has changed enough here that it might be good to have a separate conversation/create a spec document, let me know if that would be useful. 

ANSWERS TO SPECIFIC QUESTIONS ABOVE:

> Once the licence has expired will they have access to their data to download it, even though they can no longer create new studies or are they completely blocked from logging into the system?

They should be able to log in. 

> Once a licence has expired, should any parent attempting to complete a previously sent link be blocked/prevented from completing (I assume yes, but just checking)?

I would say no on that. 

> Do you want an email sent once a week during last 30 days to remind them to renew licence?

Yes, that'd be great. 

> Currently, when a researcher applies for access they need to be confirmed by an administrator. Do you want the registration page changed such that there is a check box for "Commerical User" which will automatically register the user and automatically give them access to the CAT CDIs?

I think we want to let people register automatically - and in fact, they should be able to register a FREE account and get access to all unlicensed instruments. 

> Do you want functionality to prevent an administrator from giving a Commercial User access to non CAT CDIs?

I don't think so.

> Do you want licence expiry date shown on the Researcher Interface so they always have a reminder?

Good idea. 

> Do I need to know anything about taxes? I assume this is being billed in California so do I need to add state taxes or anything like that to the $500, or is it included in the $500. Does this need to be separate line items for the user?

Actually, we are going to collect money through Brookes Publishing, so they are going to collect the money from them. All we need to do is have commercial users put in LICENSE CODES to unlock specific instrument functionality. 

> Do you want to change the Researcher Interface to make it multilingual? At the moment English is forced on everyone

Not at the moment. 

> Do you want a x day free trial available in order to encourage trying it out?

When you make a free account on the site, you should be able to see and use any free instrument.

**Comment by mcfrank** [comment]
noting links to this discussion: #338

**Comment by HenryMehta** [comment]
@mcfrank Thanks for responses Mike.  A couple of issues.  
1. I have a bunch of changes in dev which I would rather put live first, but one of those is changing the benchmark values which you don't want to put live until Jan 1st having given users notice (I haven't seen a note yet but may have been left off the list).  I can get around this issue by creating a separate development branch and test environment.  It is just more work and then I would need to retest everything currently in dev to ensure I haven't created clashes.
2. I'm super busy and it might be a few weeks (gut instinct says November) before I can free up the time again.  Having said that, if really urgent I can discuss juggling bits with other clients
3.

**Comment by mcfrank** [comment]
OK in that case, let's wait on this feature.

LookIt is ready to deploy - it has just been tricky to get the users to
test it!

**Comment by HenryMehta** [comment]
@mcfrank LookIt is deployed and I cannot make updates to WebCDI at the moment until we go live with the updated  Benchmark https://github.com/langcog/web-cdi/issues/397.  I cannot find the actually chat (it is proabably in Slack), that you're going to let the user base know they will be changing on 1st of Jan
