### ISSUE TITLE
WG "Places To Go" sections doesn't have any items

### ISSUE THREAD

**Issue by mikabr** [langcog/web-cdi#41]

**Comment by bengittelson** [comment]
@mcfrank @vmarchman

**Comment by daniellekellier** [comment]
Since there are no words in the "places" category in the instrument csv, we can drop that section in the English_WG.json or add words with that category to the csv

**Comment by vmarchman** [comment]
If I'm understanding this correctly, we should add the following words to
the places to go section.

backyard
beach
church
flower
garden
home
house
moon
outside
park
party
pool
rain
rock
school
shovel
sky
slide
snow
star
store
sun
swing
tree
water
work
zoo

**Comment by mcfrank** [comment]
Huh - there should be some places in the list? You can look in wordbank for
the items in that section...

Mike

**Comment by daniellekellier** [comment]
From the looks of it, the English_WG form in wordbank does not have items in the "places" category (Places to Go) but does have items in the "outside" category (Outside Things And Places to Go). The webcdi WG instrument looks like a copy of the wordbank instrument so that would explain the empty category.

**Comment by mcfrank** [comment]
Huh - so should we be fixing this in Wordbank too?

thanks!

**Comment by daniellekellier** [comment]
I guess that is up to preference? If you want to split up the combined categories on wordbank, I think that would require resetting, deleting the instrument, and then re-uploading the instrument (and the kids) but I don't know if that's the smartest way to do it (probably not). @mikabr what do you think?

**Comment by mikabr** [comment]
I'm not following the issue – my understanding is that the WG form itself doesn't have separate "places" and "outside" categories, but rather one "uutside things and places to go" category, which is also what Wordbank has.

**Comment by daniellekellier** [comment]
Yup, and the question is whether or not to split up that combined category or to keep it together. 

If we keep the combined category, the English_WG json file in the WebCDI would just need the "places" category deleted since all its terms are already in the combined category.

If we split up the categories, we would have to change the categories for several items in the English_WG instruments in both the webcdi and in wordbank.

**Comment by mikabr** [comment]
don't we want to do what's on the actual WG form?

**Comment by vmarchman** [comment]
That's what I think.

**Comment by mcfrank** [comment]
see virginia's slack message on this

Mike
