### ISSUE TITLE
Administration Deletion

### ISSUE THREAD

**Issue by HenryMehta** [langcog/web-cdi#465]
Instead of deleting administrations, could they be set to archived only

**Comment by HenryMehta** [comment]
@vmarchman deployed to dev for testing.  If you delete in the researcher screen, you can still find them with is_active=False in the admin section

**Comment by vmarchman** [comment]
@Henry ***@***.***> Looks great.  I could delete and then recover
administrations.  Thanks!

One suggestion, in the is_active=False menu, if you select on the
administration, then the drop down menu only gives one choice "delete
administration".  You have to go into each administration to restore it by
clicking on the "is active?" button.

Can we add "restore administration" to the drop down menu so that you could
do multiple at a time?

If not, it's ok.

-vm

**Comment by HenryMehta** [comment]
@vmarchman I've assumed you mean within Admin.  I have added and deployed to dev
