### ISSUE TITLE
indications for required fields

### ISSUE THREAD

**Issue by mikabr** [langcog/web-cdi#51]
Currently an asterisk. Could be red? Almost all fields are required, though, so it's a bit cluttered.

**Comment by bengittelson** [comment]
I think it's fine with the asterisks, but I'm happy to change it to red. Thoughts?

**Comment by mcfrank** [comment]
Red asterisks seems conventional.

Mike

**Comment by daniellekellier** [comment]
You have to edit the field.html files (bootstrap3/field.html and uni_form/field.html) within the /web-cdi/webcdi/venv/lib/python2.7/site-packages/crispy_forms/templates folder to do this.
Basically just replace 
"<span class="asteriskField">*</span>" with
"<span class="asteriskField"><font color = "aa0000">*</font></span>". There is no easy way to push these changes because the venv folder is not tracked.

**Comment by mcfrank** [comment]
Huh. that seems odd! but then let's not fix it for now and mark this as an
#enhancement?


Mike
