### ISSUE TITLE
child DOB won't save

### ISSUE THREAD

**Issue by bengittelson** [langcog/web-cdi#56]
The child DOB kept disappearing for me after I entered it and saved the form (although this was on a very old Windows computer).

**Comment by bengittelson** [comment]
I've replicated this problem in a number of different browsers and am assuming it's a problem with datepicker. The birthdate shows up when I first enter it, but it disappears if I go to the next page and then come back to the first one. @AshwinParanjape , do you have any thoughts on why this might be happening?

**Comment by bengittelson** [comment]
This happens on both the live version and my local installation.

**Comment by daniellekellier** [comment]
Child DOB does not reappear because it was never saved in BackgroundInfo. If it is added to BackgroundInfo, it will repopulate but then it finds its way into the database. Even if we cleared DOB with the form completion, I believe a researcher can access the in-progress form and see the DOB? 
For now, it might be best to warn users that the DOB will erase even if the page is saved. I added another field that shows the Age in Months to users.
